### ISSUE TITLE
Errors related to sfe.postprocess.viewer

### ISSUE THREAD

**Issue by brylie** [sfepy/sfepy-docker#2]
I have started the `sfepy/sfepy-notebook` container and launched Jupyter Lab from within the container. When trying to import `sfepy.postprocess.viewer.Viewer`, I get the following errors in the container shell:

```
sfepy_container | qt.qpa.xcb: could not connect to display :99.0
sfepy_container | qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
sfepy_container | This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
sfepy_container | 
sfepy_container | Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.
```

How can I view the VTK output? Is there a way to view it using WebGL instead of Qt?

**Comment by BubuLK** [comment]
There are still some unresolved issuess we are working on (se https://github.com/sfepy/sfepy-docker#limitations).
In the meantime, please, try using `sfepy-desktop` image instead.

**Comment by BubuLK** [comment]
This image is no longer supported/updated. Please use `sfepy-desktop` instead.
