### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by brylie** [sfepy/sfepy-docker#3]
When running the command `python sfepy_x11vnc_desktop.py` I get the following error:

```sh
Starting up docker image...
Traceback (most recent call last):
  File "/home/brylie/tmp/sfepy_x11vnc_desktop.py", line 503, in <module>
    main()
  File "/home/brylie/tmp/sfepy_x11vnc_desktop.py", line 336, in main
    size = get_screen_resolution()
  File "/home/brylie/tmp/sfepy_x11vnc_desktop.py", line 199, in get_screen_resolution
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by BubuLK** [comment]
The Tcl/Tk Python interface is probably missing/broken in your local Python configuration.

Please try to install python3-tk package (depending on your OS/Python distribution):

    pip install python3-tk
    sudo apt-get install python3-tk

Alternatively you can specify screen resolution directly from command line:

    python sfepy_x11vnc_desktop.py --size 1440x900

Regards,
LK
