### ISSUE TITLE
Add `itkwidgets` support to `sfepy/sfepy-notebook` image?

### ISSUE THREAD

**Issue by brylie** [sfepy/sfepy-docker#4]
It would be nice to render vtk output directly within a Jupyter (Lab) notebook. The [itkwidgets](https://pypi.org/project/itkwidgets/) provides interactive Jupyter widgets to visualize images, point sets, and meshes on the web.

![itkwidgets screenshot](https://warehouse-camo.ingress.cmh1.psfhosted.org/b4dbf6b9c5d36361d54cf098be353e4cf0768746/68747470733a2f2f692e696d6775722e636f6d2f643861587963572e706e67)

How can I ensure that `itkwidgets` gets installed when building the `sfepy-notebook` container? Is it possible to define a local `package.json` with the `itkwidgets` dependency and have `sfepy-notebook` automatically install the `package.json`?

**Comment by BubuLK** [comment]
`itkwidgets` are actually installed in docker image, but there are still some unresolved issuess we are working on...

Inside you container you can install any OS/Python package of your choice from commandline.
Please feel free experiment with your exaples ale let us know any suggestion or improvments (via Issue/PR) we could made.

P.S.: Thanks for your suggestion: we could add functionality for installing user-defined packages in next release.

**Comment by BubuLK** [comment]
This image is no longer supported/updated. Please use `sfepy-desktop` instead.
